### ISSUE TITLE
Adding Movies Error

### ISSUE THREAD

**Issue by HDVinnie** [ArnaudLevaufre/Cinema#1]
So I got the site up and running on local machine but no films added.

When i try to add a movie directory and update as said in ready i get following issues.

MacBook-Pro:Cinema-master Vinnie$ ./manage.py add /Users/Vinnie/Public
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/**init**.py", line 350, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/**init**.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/**init**.py", line 195, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Library/Python/2.7/site-packages/django/core/management/**init**.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
ImportError: No module named management.commands.add

MacBook-Pro:Cinema-master Vinnie$ ./manage.py update
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/**init**.py", line 350, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/**init**.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/**init**.py", line 195, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Library/Python/2.7/site-packages/django/core/management/**init**.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
ImportError: No module named management.commands.update

**Comment by HDVinnie** [comment]
solved
