### ISSUE TITLE
"ValueError: Set of coroutines/Futures is empty" on update

### ISSUE THREAD

**Issue by stephanepechard** [ArnaudLevaufre/Cinema#3]
On a directory update with only one file (marked as SAMPLE), I get a `ValueError` and the script crashes. I don't know `asyncio` to look further down into the problem.
I try to play a bit with your code, so you should know that the file used is not a genuine one. It's in fact a 0kb file made with `touch` to test Cinema. I don't know if you try to open the file, so maybe it is the reason of the crash, but still, it should not crash :-)
Tell me if you need more information. Here is the stack trace:

    (venv) ➜  Cinema git:(master) ✗ ./manage.py update
    Creating a client session outside of coroutine
    client_session: <aiohttp.client.ClientSession object at 0x103281940>
    [            SAMPLE             ] /tmp/cine/North.by.Northwest.1959.720p.BluRay.x264-CtrlHD.mkv
    Traceback (most recent call last):
      File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/tmp/Cinema/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
        utility.execute()
      File "/tmp/Cinema/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/tmp/Cinema/venv/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/tmp/Cinema/venv/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
        output = self.handle(*args, **options)
      File "/tmp/Cinema/application/management/commands/update.py", line 142, in handle
        loop.run_until_complete(asyncio.wait(tasks))
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
        return future.result()
      File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 304, in wait
        raise ValueError('Set of coroutines/Futures is empty.')
    ValueError: Set of coroutines/Futures is empty.
    Unclosed client session
    client_session: <aiohttp.client.ClientSession object at 0x103281940>

**Comment by stephanepechard** [comment]
Going further down with my trials, I don't get this crash when I have another genuine file in the same directory.

**Comment by ArnaudLevaufre** [comment]
Interesting. The crawler creates a list of tasks to import each files detected as movies. In the initialization phase the dummy file is detected as a sample (file size < 256MB) and thus no import task is created. In the end, there is not task to execute so asyncio don't know what to do with our empty set of task.

Thanks a lot for the bug report, I'm pushing a fix to the master ASAP.

**Comment by stephanepechard** [comment]
Thanks for the fast fixing 👍
